import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import styles from '@/app/page.module.css';
import ReactQuery from './provider/react-query';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'mong',
    description: 'Generated by create next app',
};

type Props = {
    children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReactQuery>{children}</ReactQuery>
            </body>
        </html>
    );
}
